controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

sensors_routes:
    path: /sensors
    controller: App\Controller\SensorsController::index
    methods: GET

sensors_create:
    path: /sensors/create
    controller: App\Controller\SensorsController::create
    methods: POST